---
- name: Tao vm - ip tren netbox
  hosts: localhost
  gather_facts: true
  connection: local

  tasks:
    - name: Sending contents of a file in the email body
      mail:
       host: mail.smtp2go.com
       port: 2525 
       username: XXXXXXXXXXX
       password: XXXXXXXXXXXXXXXXX
       from: admin@vlphere.com
       to: tcvn1985@gmail.com
       subject: Change log
       body: "{{ lookup('template','templates/email-template-demo.html.j2') }}"
       subtype: html
      delegate_to: localhost    
